### ISSUE TITLE
Issue related to "Quickstart/Setup a Kuzzle Backoffice" section

### ISSUE THREAD

**Issue by meepeek** [kuzzleio/kuzzle-guide#37]
Pre-made back office is very interesting. However, I follow the tutorial backoffice is not working

![screen shot 2559-08-05 at 3 34 56 pm](https://cloud.githubusercontent.com/assets/2456033/17431093/55eb43ca-5b22-11e6-9035-b23d8a073017.png)

**Comment by j33f** [comment]
Hello

which steps did you follow to install your back office (in order to reproduce) ?

**Comment by meepeek** [comment]
Hi, this is the compose script I used
```
redis:
  image: redis:3.0-alpine
kuzzle:
  image: kuzzleio/kuzzle:1.0.0-RC4
  links:
  - redis:redis
  - elasticsearch:elasticsearch
  - proxy:api
kuzzleBo:
  ports:
  - 3000:3000/tcp
  image: kuzzleio/bo:latest
  links:
  - proxy:kuzzle
proxy:
  ports:
  - 7511:7511/tcp
  - 7512:7512/tcp
  image: kuzzleio/proxy:alpine
elasticsearch:
  image: kuzzleio/elasticsearch:2.2
```
